import Head from 'next/head';
import { Header } from '../../components/Header';
import Hero from './hero';

export default function Home() {
  return (
    <>
      <Head>
        <title>Quiz App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
        <link
          href='https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.4/flowbite.min.css'
          rel='stylesheet'
        />
        <script src='https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.4/flowbite.min.js' />
      </Head>

      <Hero />
    </>
  );
}
